name: decision_maker
description: A new Flutter application to make important decisions.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: "^0.4.2"
  flutter_circular_chart: "^0.0.3"
  flutter_walkthrough:
  sqflite: any
  path_provider: "^0.3.1"
  flutter_billing: "^0.2.2"
  firebase_auth: "^0.5.11"
  firebase_analytics: "^1.0.1"
  firebase_core: "^0.2.4"
  firebase_database: "^1.0.1"
  cloud_firestore: "^0.7.3"
  package_info: "^0.3.2"
  font_awesome_flutter: "^7.0.0"
  url_launcher: "^3.0.2"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/decision-making.png
    - assets/image/criteria.png
    - assets/image/options.png
    - assets/image/people.png
    - assets/image/pie-chart.png
    - assets/image/rate.png
    - assets/image/result.png
    - assets/image/dev.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 70
 
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
